---
- name: Testing andrewrothstein.spire
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'spire-server --verseion'
      ansible.builtin.command: spire-server --version
      changed_when: false
      register: spire_test_output
    - name: Output from 'spire-server --version'
      ansible.builtin.debug:
        msg: '{{ spire_test_output.stderr }}'
