---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/spire-server --version
      register: spire_test_output
    - name: spire-server --version
      debug:
        msg: '{{ spire_test_output.stderr }}'
