---
- include_role:
    name: andrewrothstein.unarchivedeps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install...
  become: true
  stat:
    path: '{{ spire_install_dir }}'
  changed_when: false
  register: spire_binary
- when: not spire_binary.stat.exists
  block:
    - name: download archive...
      become: true
      become_user: root
      get_url:
        url: '{{ spire_url }}'
        dest: '{{ spire_tmp_tgz }}'
        mode: 0644
        checksum: '{{ spire_checksum }}'
    - name: unarchiving {{ spire_tmp_tgz }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ spire_tmp_tgz }}'
        dest: '{{ spire_parent_install_dir }}'
        creates: '{{ spire_install_dir }}'
  always:
    - name: rm -f {{ spire_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ spire_tmp_tgz }}'
        state: absent
- name: link install dir
  become: true
  become_user: root
  file:
    src: '{{ spire_install_dir }}'
    dest: '{{ spire_link_dir }}'
    state: link
- name: link bins
  become: true
  become_user: root
  with_items:
    - spire-server
    - spire-agent
  file:
    src: '{{ spire_link_dir }}/bin/{{ item }}'
    dest: '{{ spire_parent_install_dir }}/bin/{{ item }}'
    state: link
